//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::stats::{
    Entity as Stats,
    ActiveModel as StatsActiveModel,
    Column as StatsColumn,
    Model as StatsModel,
    PrimaryKey as ModelPrimaryKey,
};
